config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  resources :players

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end

  def new
  @player = Player.new
  end

  def create
  	@player = Player.new (players_params)
  	if @player.save 
  		redirect_to root_path
  	end
  end

  def show
  	@player = PLayer.new (players_params)
  	if @player.save 
  		redirect_to root_path
  	end
  end
  def edit
  	@player = Player.find(params[:id])
  end

  def update
  	@player = Player.find(params[:id])
  	@player.update(player_params)
  	if @player.save
  		redirect_to player_path(@post.id)
    end

 def destroy
  	@player = Player.find(params[:id])
  	redirect_to root_path
    @player.delete()
  	
  end

  private 
    def player_params
      params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player url: players_path do |f| %>
<%= form.text_field :nickname %>
<%= form.text_field :rank %>
<%= form.text_field :charisma %>
<%= form.text_field :wisdom %>
<%= f.submit "Edit" %>

app/views/players/index.html.erb
<% if @players == [] %>

<p> 
	<% else %>
	<% @player.each do |player| %>
		<%= player.nickname  %><br/>
		<%= player.rank  %><br/>
		<%= player.charisma %><br/>
		<%= player.wisdom  %><br/>

		<%= link_to "Details" , players_path(player.id) %></p>>
		<% end %>
	<% end  %>

<%= link_to "Add new player", new_players_path %>

app/views/players/new.html.erb
<%= form_for @player url: players_path do |f| %>
<%= form.text_field :nickname %>
<%= form.text_field :rank %>
<%= form.text_field :charisma %>
<%= form.text_field :wisdom %>
<%= f.submit "Create" %>

app/views/players/show.html.erb
<p> 
 <%= @player.nickname %><br />
 <%= @player.rank %><br />
 <%= @player.charisma %><br />
 <%= @player.wisdom  %><br />
</p>

<p> 
	<%= link_to "Edit" , edit_players_path(@player.id) %><br />
	<%= link_to "Destroy" , players_path, :method => :delete %>
	</p>